name: Frex workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler: [ 'ocaml-variants.4.11.1+BER', 'ocaml-variants.4.14.1+BER' ]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - run: opam install . --with-test
